#!/bin/sh
set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)
IMAGE=${1:-kiln:core-local}
BUSYBOX_IMAGE=${2:-busybox:1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616}

KILN_SMOKE_CHECK_RESOURCES=1 \
KILN_SMOKE_CPUS=${KILN_CORE_SMOKE_CPUS:-1} \
KILN_SMOKE_MEMORY=${KILN_CORE_SMOKE_MEMORY:-128m} \
KILN_SMOKE_MAX_PEAK_BYTES=${KILN_CORE_SMOKE_MAX_PEAK_BYTES:-125829120} \
KILN_SMOKE_ITERATIONS=${KILN_CORE_SMOKE_ITERATIONS:-20} \
KILN_SMOKE_MAX_RSS_KB=${KILN_CORE_SMOKE_MAX_RSS_KB:-65536} \
KILN_SMOKE_VARIANT=core \
KILN_SMOKE_HEALTHCHECK_MODE=external \
KILN_SMOKE_EXPECTED_PROFILE=compact \
KILN_SMOKE_EXPECTED_MEMORY_LIMIT_MB=48 \
KILN_SMOKE_EXPECTED_INFLIGHT_MB=32 \
KILN_SMOKE_EXPECTED_MAX_SEGMENT_MB=20 \
KILN_SMOKE_EXPECTED_GC_PERCENT=75 \
  sh "$ROOT/deploy/docker/native-media-runtime-smoke.sh" "$IMAGE" "$BUSYBOX_IMAGE"
